#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

exit 0
REGEX_ISSUE_ID="[a-zA-Z0-9,\.\_\-]+-[0-9]+"

NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

# Find current branch name
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Extract issue id from branch name
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")

if [[ -z "$ISSUE_ID" ]]; then
    echo -e "${BRed}Branch doesn't have Jira task code on itq... ${NC}"
    echo -e "${BBlue}You can use ${BRed}git commit -m \"\" --no-verify${BBlue} to avoid this hook.${NC}"
    exit 1
fi

PREFIX=$(echo $ISSUE_ID | awk 'BEGIN { getline; print toupper($0) }')

echo "$PREFIX"': '$(cat "$1") > "$1"
